version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loadbalancer-app
    env_file:
      - .env  # Load environment variables from .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app